update actions

diff --git a/.github/actions/trigger-binder-action/action.yml b/.github/actions/trigger-binder-action/action.yml
--- a/.github/actions/trigger-binder-action/action.yml
+++ b/.github/actions/trigger-binder-action/action.yml
@@ -20,4 +20,30 @@ runs:
         INPUT_TOKEN: ${{ inputs.binder_token }}
       # TODO: authentication
       run: |
-        bash trigger_binder.sh "${INPUT_BINDER_LAUNCH_URL}"
+        #!/usr/bin/env bash
+        # From https://github.com/scikit-hep/pyhf/blob/v0.7.6/binder/trigger_binder.sh
+
+          function trigger_binder() {
+          local URL="${1}"
+
+          curl -L --connect-timeout 10 --max-time 30 "${URL}"
+          curl_return=$?
+
+          # Return code 28 is when the --max-time is reached
+          if [ "${curl_return}" -eq 0 ] || [ "${curl_return}" -eq 28 ]; then
+          if [[ "${curl_return}" -eq 28 ]]; then
+          printf "\nBinder build started.\nCheck back soon.\n"
+          fi
+          else
+          return "${curl_return}"
+          fi
+
+          return 0
+        }
+
+          function main() {
+          # 1: the Binder build API URL to curl
+          trigger_binder $1
+        }
+
+          main "${INPUT_BINDER_LAUNCH_URL}" || exit 1
